# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PIL.Image import Image
from PIL import Image
from PyQt5.QtWidgets import QMainWindow, QApplication,QFileDialog,QMessageBox
from PyQt5.QtGui import QPixmap
import sys
from PIL.ImageQt import ImageQt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt

from EigenFaces import FacesFeatures
class Ui_MainWindow(QMainWindow):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageView = QtWidgets.QGraphicsView(self.centralwidget)
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.setView = QtWidgets.QGraphicsView(self.centralwidget)
        self.setView.setObjectName("setView")
        self.verticalLayout_2.addWidget(self.setView)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionface_Recognition = QtWidgets.QAction(MainWindow)
        self.actionface_Recognition.setObjectName("actionface_Recognition")

        

        self.pushButton.clicked.connect(self.open_image)
        
        self.FaceRecongnizer=FacesFeatures()
        self.FaceRecongnizer.IntializeDataMatrix()
        self.FaceRecongnizer.GetEigenFaces()
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "open image"))
        self.actionOpenImage.setText(_translate("MainWindow", "open"))
        self.actionface_Recognition.setText(_translate("MainWindow", "face Recognition"))

    def open_image(self): 
               
        self.fname = QFileDialog.getOpenFileName(self, "Open File", "c:\\gui\\images", "All Files (*);;PNG Files (*.png);;Jpg Files (*.jpg);;PGM Files (*.pgm)" )
        #Open The Image
        self.img = Image.open(self.fname[0])
        self.qimage = ImageQt(self.img)
        self.pixmap = QPixmap.fromImage(self.qimage)
        self.item = QtWidgets.QGraphicsPixmapItem(self.pixmap)
        self.scene = QtWidgets.QGraphicsScene(self)
        self.scene.clear()
        self.scene.addItem(self.item)
        self.imageView.setScene(self.scene)
        self.Recognize()

    def Recognize(self):
        self.FaceRecongnizer.RecognizeFace(self.fname[0])

if __name__ =="__main__":
    app = QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui= Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())